# Generated by Django 6.0.3 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_img", models.ImageField(upload_to="banners/")),
                ("alt_text", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("detail", models.TextField()),
                ("service_img", models.ImageField(null=True, upload_to="services/")),
            ],
        ),
    ]
